# DO NOT CHANGE THIS FILE, EDIT CONFIGURATIONS AT application.yml
default: &default
  adapter:  postgresql
  database: <%= ENV['DATABASE_DATABASE'] %>
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV['DATABASE_POOL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  template: template0
  username: <%= ENV['DATABASE_USERNAME'] %>

development:
  <<: *default
test:
  <<: *default
  database: <%= ENV['DATABASE_DATABASE'] %>
production:
  <<: *default
# DO NOT CHANGE THIS FILE, EDIT CONFIGURATIONS AT application.yml
